#!/bin/bash
# Blue View OS sky for the web: assembles a self-contained page in dist/web from
# the shared sources in web/ and the Omarchy plugin (astronomy, SGP4, shader,
# star catalogue, logo), so every platform draws the same sky.
#
# Copyright (c) 2026 The Blue View Group Corporation. Author: Frank Perez <frank@blueview.ai>
# Licensed under the PolyForm Noncommercial License 1.0.0. See LICENSE.
#
# Usage: web/build.sh [output-dir]    (default: dist/web)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLUGIN="$ROOT/omarchy/plugins/bvos.screensaver"
OUT="${1:-$ROOT/dist/web}"
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/bvos/web-build"

# "file url" pairs (plain lists, so this also runs on macOS's bash 3.2)
FONTS=(
  "Geist-Variable.ttf https://github.com/google/fonts/raw/main/ofl/geist/Geist%5Bwght%5D.ttf"
  "Manrope-Variable.ttf https://github.com/google/fonts/raw/main/ofl/manrope/Manrope%5Bwght%5D.ttf"
  "weathericons-regular-webfont.woff2 https://github.com/erikflowers/weather-icons/raw/master/font/weathericons-regular-webfont.woff2"
)

rm -rf "$OUT"
mkdir -p "$OUT/generated" "$OUT/fonts" "$CACHE"

cp "$ROOT"/web/{index.html,style.css,app.js,weather.js,sky-gl.js,stars.js,satellites.js} "$OUT/"
cp "$PLUGIN/blueview-logo.svg" "$OUT/"
cp "$PLUGIN/LICENSE.satellite-js" "$PLUGIN/LICENSE.d3-celestial" "$ROOT/LICENSE" "$ROOT/NOTICE" "$OUT/"

for font in "${FONTS[@]}"; do
  name=${font%% *}
  url=${font#* }
  if [[ ! -s $CACHE/$name ]]; then
    curl -fsSL "$url" -o "$CACHE/$name.new" && mv "$CACHE/$name.new" "$CACHE/$name"
  fi
  cp "$CACHE/$name" "$OUT/fonts/"
done
cat >"$OUT/fonts/FONTS.txt" <<'TXT'
Geist (c) The Geist Project Authors, Manrope (c) The Manrope Project Authors, and
Weather Icons (c) Erik Flowers are licensed under the SIL Open Font License 1.1
(https://openfontlicense.org).
TXT

python3 - "$PLUGIN" "$OUT/generated" <<'PY'
import json, re, sys
plugin, out = sys.argv[1], sys.argv[2]
HEADER = "// Generated by web/build.sh from omarchy/plugins/bvos.screensaver. Do not edit.\n"

def strip_pragma(text):
    return re.sub(r"^\.pragma library\s*$", "", text, flags=re.M)

# Astro.js is a QML JavaScript library; wrap it as a global for the page.
astro = strip_pragma(open(f"{plugin}/Astro.js").read())
exports = sorted(set(re.findall(r"^function (\w+)", astro, flags=re.M)) | set(re.findall(r"^var (\w+)", astro, flags=re.M)))
open(f"{out}/astro.js", "w").write(HEADER + "const Astro = (function () {\n" + astro +
    "\nreturn { " + ", ".join(exports) + " }\n})()\n")

sgp4 = strip_pragma(open(f"{plugin}/SGP4.js").read())
open(f"{out}/sgp4.js", "w").write(HEADER + "const SGP4 = (function () {\n" + sgp4 + "\nreturn { satellite: satellite }\n})()\n")

# sky.glsl is Vulkan-style GLSL 440 for Qt; turn its header into GLSL ES 3.00 for WebGL 2.
glsl = open(f"{plugin}/sky.glsl").read()
block = re.search(r"layout\(std140, binding = 0\) uniform buf \{(.*?)\};", glsl, flags=re.S)
uniforms = []
for line in block.group(1).splitlines():
    decl = line.split("//")[0].strip().rstrip(";")
    if decl:
        kind, name = decl.split()
        uniforms.append([name, kind])
body = glsl[block.end():]
header = "precision highp float;\nin vec2 qt_TexCoord0;\nout vec4 fragColor;\n" + "".join(f"uniform {k} {n};\n" for n, k in uniforms)
shader = {"uniforms": uniforms, "body": header + body}
open(f"{out}/sky-shader.js", "w").write(HEADER +
    "const BVOS_SKY_SHADER = " + json.dumps(shader) + "\n" +
    "BVOS_SKY_SHADER.fragment = pass => \"#version 300 es\\n#define \" + pass + \"\\n\" + BVOS_SKY_SHADER.body\n")

stars = json.load(open(f"{plugin}/stars.json"))
lines = json.load(open(f"{plugin}/constellations.json"))
open(f"{out}/star-data.js", "w").write(HEADER + "// " + stars["source"] + "\n// " + lines["source"] + "\n" +
    "const BVOS_STAR_DATA = " + json.dumps({"stars": stars["stars"], "constellations": lines["constellations"]}, separators=(",", ":")) + "\n")
PY

echo "Built $OUT"
